### ISSUE TITLE
Seems like a bug that params not getting ?

### ISSUE THREAD

**Issue by harikt** [auraphp/Aura.Dispatcher#7]
Not sure why the `$params`  is not getting.

``` php
<?php
$loader = require __DIR__ . '/vendor/autoload.php';

use Aura\Dispatcher\InvokeMethodTrait;

class Blog
{
    use InvokeMethodTrait;

    public function __invoke($params)
    {
        $action = isset($params['action']) ? $params['action'] : 'index';
        $method = 'action' . ucfirst($action);
        return $this->invokeMethod($this, $method, $params);
    }

    protected function actionIndex()
    {
        return "I am from index";
    }

    protected function actionRead($id = null)
    {
        return "Read blog entry $id";
    }
}

use Aura\Dispatcher\Dispatcher;

$dispatcher = new Dispatcher;
$dispatcher->setObjectParam('controller');

$dispatcher->setObject('blog', function () {
    return new Blog();
});

$params = [
    'controller' => 'blog',
    'action' => 'read',
    'id' => 88,
];

$result = $dispatcher->__invoke($params);
echo $result; // Read blog entry 88
```

**Comment by pmjones** [comment]
Definitely a bug. In Dispatcher, line 117 is:

```
$result = $this->invokeMethod($object, '__invoke', $params);
```

The problem is that it tries to match 'action', 'controller', 'id' to __invoke($action, $controller, $id), and **not** to __invoke($params).  This is actually doing what we have told it, although it is not what we want. I'll think about how to solve this.  Thanks man.

**Comment by pmjones** [comment]
The latest commit https://github.com/auraphp/Aura.Dispatcher/commit/9b5053d2a57305414081774527d60797a7644929 treats a function argument `$_params` as a special case. Args named `$_params` will receive the `$params` array directly from the dispatcher (instead of looking for `$params['_params']`).  If you change your method signature from `__invoke($params)` to `__invoke($_params)` and use `$_params` in the method, then it should work.

I am not entirely happy with this, since it imposes a special case on dispatchable objects.  I am likewise not entirely happy with the name `$_params` -- it needs to be something not likely to be used in routers, and this seems unlikely, but still.

Thoughts?

**Comment by harikt** [comment]
Frankly saying I don't like that way, so I made a work around for you will ask me how we can do else ;) .

https://github.com/auraphp/Aura.Dispatcher/pull/8

**Comment by harikt** [comment]
Sorry for I wasn't able to take your test case first and merge.

**Comment by harikt** [comment]
Early morning, let me brush my teeth and come ;) .

**Comment by pmjones** [comment]
I think this has been fixed; please let me know if you're still having trouble and we can re-open.

**Comment by harikt** [comment]
yes, we fixed.

Thanks.
